### ISSUE TITLE
Check comments on documentation, as per commit 52

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#103]
Please take a look at the comments in the documentation:
https://github.com/aiorazabala/qmethod/pull/52/files#diff-6c40e1e5d97aa249ebf9296ce4f2d37c

I finished reviewing it all. The comments are based on the latest package version in master (which is not exactly the same code as in the link above, but the comments should be sufficiently understandable). Please take all of them as suggestions, they are for clarity (so that users easily understand what the function does, and hopefully use them!) and consistency (to give more sense of a reliable code).

Some of the comments might apply to more than one documentation page but I didn't write them in all the documentation files. I suggest to give all the documentation a quick read/review before it's sent for prime.

These are some general points:
* Referral to files still have some small inconsistencies: .TEX and CSV mixed (with or without dot)
* I'm still confused with 'handle', 'hash', 'meaningful short item handle' etc. I suspect that they're all the same thing, correct? I suggest that you choose one short term and stick throughout (e.g. 'handle'). If it is defined somewhere (e.g. in qmethod-package), indicating that it should be short and meaningful, then it doesn't need to be repeated in full elsewhere (otherwise it can be confusing, as the reader may think that these are different things).

**Comment by maxheld83** [comment]
wow, that's a lot of comments, thanks @aiorazabala 
I hope to get through them tomorrow.

**Comment by aiorazabala** [comment]
Hey, please check the updated comment. Hope the feedback makes sense!

**Comment by maxheld83** [comment]
it's done.
Thanks so much for the thorough feedback – you're really a perfectionist @aiorazabala :)

Two small suggestions for the future:

1. if you find a small mistake, or see a better formulation, feel free to edit it right away – after all, it's always revertible and it's more efficient.
2. if you're looking for things to comment on you don't see in the diff, you can always comment on complete commits.
