### ISSUE TITLE
specify coding style for qmethod dev

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#11]
https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml seems to be popular.

**Comment by maxheld83** [comment]
I think the coding style is getting along well, and I'm trying to get the hang of the existing style, to make sure my (small) additions fit in.

Just a couple of small suggestions:

- Can we try and stick to the **80 char** limit per line, and if at all possible, split + indent the line if we're longer than that?
- For prose as (as in `man` or on `wiki.qmethod`), can we add a **newline after every sentence**? Both markdown and LaTeX ignore those anyway. 
- I'd suggest we generally (but sticking to Google's R code) use a **bit more linebreaks and two-space indentation**.

All of this might make code easier to read, and, crucially for `git`, give us more meaningful `git diff`s, because those are *line*-based.

Anyway, this is obviously only for future edits, no need to change anything existing.

Would it be ok if I added some more linebreaks and indentiation as per the above, if I ever edit something, @aiorazabala ?

**Comment by aiorazabala** [comment]
Fine. Please don't change that in the functions that I authored, I'll do that whenever I update them. 
Is the 80 character number a standard one? And the new line after every sentence? (Do you use soft-wrap in your R editor?)

**Comment by maxheld83** [comment]
Absolutely – I won't touch any existing code! Sorry if I gave that impression.
It's just that when I write something (as in the import/export functions) I like to use indents/linebreaks quite liberally, just to help me get my head around it.

Google's R coding style does seem to suggest a 80 character limit ([here](https://google-styleguide.googlecode.com/svn/trunk/Rguide.xml#linelength)).

The new line after every sentence for prose isn't in from any programming style guide I know, it's just something that some LaTeX / Markdown users recommend 
([here](http://tex.stackexchange.com/questions/4376/good-strategy-for-line-breaks-with-paragraphs-of-latex-source),
[here](http://rhodesmill.org/brandon/2012/one-sentence-per-line/),
[here](http://stackoverflow.com/questions/899114/when-you-write-tex-source-how-do-you-use-your-editors-word-wrap)), 
especially for better TeX/Pandoc errors (they're line-based) and easier version control.
No technical reason per se, just convenience and convention.

Anyway, I apologize for raising coding styles again, which with I seem to have some kind of weird obsession :).
I'll follow the most important rule (which is also in Google's R style): make contributions fit in nicely with existing code :).

I might just add some more linebreaks and indents to my stuff.

**Comment by maxheld83** [comment]
uh, and yes, I have soft wrap enabled. CLOSED :)
