### ISSUE TITLE
allow import/export from Q-Assessor

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#117]
Stan Kaufman recently wrote on the list:

> I also welcome the development of this Q package for R. At the point that file formats for input of data into this package are fully specified, I intend to add an export feature to Q-Assessor to make it simple for investigators to perform online Q studies with Q-Assessor and then use R for analysis, should they want to use different/additional techniques beyond the basic processes that Q-Assessor provides. Q-Assessor now has such an export feature for PQMethod.

Maybe we should get back to him, once we've moved on a bit Release 1.3.

I was thinking that maybe the files expected by my import functions might be suitable as foarmat for Q-Assessor to write.

**Comment by aiorazabala** [comment]
Fantastic. The formats to import that I have in mind are:
-[X] PQMethod (single LIS file), in function import.pqmethod()
-[ ] FlashQ (single CSV file)
-[ ] HTMLQ (?)
-[ ] Q-Assessor (?)

These import functions should be very simple to code. They're planned already in issue #50 . The idea is to create a function for each of them (or a single function `import.q()`, with argument `format=c("PQMethod", "FlashQ", "HTMLQ", "Q-Assessor")` ). Then this (these) simple function(s) could be called from within your import functions.

I'm waiting for response from Johannes O (HTMLQ) to see how the data file looks like.

**Comment by aiorazabala** [comment]
I moved this comment to issue #55, to centralise the topic.

**Comment by maxheld83** [comment]
great, thanks @aiorazabala should've posted this to #50.
