### ISSUE TITLE
spurious travis CI build fail

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#123]
I'm trying to set up Travis continuous integration for our development (as per #88).

Unfortunately, part of my `array.viz.R` calls the package `stringr`, which causes Travis to fail (apparently intermittently).

Also reported in:
- https://github.com/Rexamine/stringi/issues/155
- https://github.com/hadley/stringr/issues/68

This seems to be an artefact of Travis, not of my code.

I'm looking for a fix for this, but the issue should stay open until the root cause in travis CI is solved (see above issues)

**Comment by aiorazabala** [comment]
Travis removed
