### ISSUE TITLE
make visualizations out of factor arrays

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#14]
It seems to be customary to either a) represent factors by a list of item z-scores or b) re-create a hypothetical, ideal-typical q-sort from the position of that factor (see Watts & Stenner 2012).

There are several types of information that we should get out of this results view:

1. the significance of items on factors
2. the "loadings" of items on factors
3. the scores (ideally as continuous, z-scored data, not *reduced* to ordinal)
4. the "holistic" big picture in a form similar to the original q-sorts, and a form that makes sure we always understand the individual items in the context of, and relative to all other items.

I was thinking of accomplishing / summarizing all of this in a **wordle**-type visualization, where

- items are represented by short, meaningful titles (maybe with full item formulation available on mouse-over for a later interactive version via shiny)
- position of short-titles on x-axis is the item scores as z-scores (same as q-sort)
- y-axis is meaningless (same as q-sort)
- font size of short-names is loading
- font color (degrees from black to greyish to white) is significance

That might give a pretty good overview.

I'll into how this might be done with existing wordle etc. packages on R.

**Comment by maxheld83** [comment]
this is the next thing I'll be working on.
I feel like I really need a better way to visually inspect my results.

**Comment by aiorazabala** [comment]
Did you check the plot() for an object of class "Qmethodres" ? See pp 8 in http://journal.r-project.org/archive/accepted/zabala.pdf

**Comment by maxheld83** [comment]
yes I did! I am working with that all the time already! Thanks so much for including that! :bouquet: 

I was thinking more of a visualization that basically reproduces the way data is entered, so an ideal-typical qsort for each factor, maybe in different colors, maybe with added info layers for consensus/distinguishing or something (see above).
I obviously haven't thought this out.

I am working with my (diss) q study that has 77 items, so I really need a way to – as some q methodologists would stress – interpret the factors *holistically*.

Ps.: Have also downloaded that paper of yours, still have to read that.

**Comment by aiorazabala** [comment]
Ah, I see sorry. 
How about the ***plot.table()*** function? Create a table where the statements are 'in the correct cell', and where there are also empty cells (to get the 'pyramid' effect), and then plot it.

**Comment by maxheld83** [comment]
here's a very early draft, qdc is still missing.

![rplot](https://cloud.githubusercontent.com/assets/5372770/6153280/e3cf98d4-b223-11e4-8024-a51216dbb97b.jpeg)

**Comment by VerenaKasztantowicz** [comment]
@maxheld83 Transparency for standard deviation seems to be good (new?) idea (and probably better than font size). It helps to keep in mind that the item positions of the "flagged/individual" q-sorts could be very different!  
I'm curious to know how the qdc-visualization works... maybe with little boxes (left, right or middle) at the bottom of each item (colored like the other factors)?

**Comment by maxheld83** [comment]
thanks @VerenaKasztantowicz !
Yeah; I'll have to be careful not to produce an illegibly overloaded graph ...

**Comment by maxheld83** [comment]
ok, here we go, now with (some amount of) `qdc.R` statements.
Lines show the *relative* position of items on the significantly different other factor (3 factors in total).
So, if a yellow line is slightly to the right of center of a card, it means that that item scored significantly more positive on the "yellow" factor.
I've also fixed the layout a little bit.

There's also different fonts, but that's a different story (specific to my study).

I think this information overload, so I'll probably just make it digital, and add a little colored corner if some item is significantly more to the left or the right.

What do you think @aiorazabala and @VerenaKasztantowicz 

![rplot](https://cloud.githubusercontent.com/assets/5372770/6179617/2b3ba350-b31b-11e4-8611-c8c1f6ce7dff.jpeg)

**Comment by aiorazabala** [comment]
Beautiful!!!

**Comment by maxheld83** [comment]
@aiorazabala I'll add these as functions soon; they are essentially **ggplot2** wrappers, but there's some data preparation and layouting necessary that people might appreciate to have ready-made.

**Comment by maxheld83** [comment]
ok this is pretty much the final version for now.
Colors automatically cycle through a color space.

Now comes documentation, testing, input validation.

![rplot02](https://cloud.githubusercontent.com/assets/5372770/6313590/c218e61c-b9b4-11e4-943f-468f18a0172a.jpeg)

**Comment by maxheld83** [comment]
we're almost there.

- [ ] improving / proofreading docs
- [ ] making the legend prettier, for different kinds of `nstats`
