### ISSUE TITLE
plot eigenvalues/eigenvector extraction of pairwise correlation (examples)

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#145]
It seems to me that while actually understandable, PCA is not very well understood in my discipline (myself included), let alone its application to Q.
So I thought it'd be nice to _really_ explain the eigenvalue/vector extraction process, using **actual Q data**.

To do this, I decided to look at a few (highest, lowest, null, identity) correlation pairs, and plot the actual eigenvalues/vectors for that on a scatterplot of items.

If other people (@aiorazabala, @verenakasztantowicz?) find this helpful, I might include it as a function.

Here's a preview.

![rplot02](https://cloud.githubusercontent.com/assets/5372770/7774920/07bd5b3a-00af-11e5-800d-22a8c0de9d41.png)

Crucially, this does _not_ help interpret the factors, it just illustrates the extraction procedure.

**Comment by aiorazabala** [comment]
Hey, looks very pretty and excellent image for teaching. 
Maybe its place could be a short sweave/knitr or web-based tutorial on PCA?

**Comment by maxheld83** [comment]
Yup.
So you think this probably shouldn't be *inside* the `qmethod()` package as a function, @aiorazabala , correct?
(That's what I came around to thinking, too).

- [ ] a) put this online as an rmarkdown piece, maybe as part of the wiki?
- [ ] b) try and add the actual plotting code to an existing PCA package, maybe [FactoExtra](http://www.sthda.com/english/wiki/factoextra-r-package-quick-multivariate-data-analysis-pca-ca-mca-and-visualization-r-software-and-data-mining)

I'll close this once I've done those things.
Must also revert commit with respective function.

**Comment by maxheld83** [comment]
this would now be considered a *vignette* as per #261 
Maybe do that-

**Comment by maxheld83** [comment]
duplicated https://github.com/QWrks/pensieve/issues/258
