### ISSUE TITLE
support (centroid) factor analysis for extraction, too

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#15]
there seems to be some debate around whether to use PCA or centroid factor analysis (with Stephen Brown arguing for the latter).

Am I correct to assume that as of know via the psych package qmethod only supports PCA, not (centroid) FA?

**Comment by maxheld83** [comment]
Noori suggested in (see #20) that in fact **PAF** and **CFA** may not consistently produce similar results, so there may still be a need for **CFA**.

**Comment by maxheld83** [comment]
[here](https://listserv.kent.edu/cgi-bin/wa.exe?A2=ind1206&L=q-method&F=&S=&X=7A14F22EEE7751DED2&Y=p41bsmk%40unibw-muenchen.de&P=63) is a very long, spirited and thoughtful discussion of Centroid vs PCA, featuring Brown and Schmolck.
I must admit I am swayed by Schmolck's arguments, which I find very persuasive.

That need not mean that centroid shouldn't be implemented in the package, but for me, it's not a top priority any more.

Anyway, at least, the discussion is a good resource on the differences between PCA and Centroid.

**Comment by aiorazabala** [comment]
Thank you, great reference!

I liked v much your contribution/question to the list, I think it was greatly and clearly formulated. Responses weren't as clear unfortunately, including some confusion between the extraction and rotation steps ('centroid rotation' ?), which adds even more noise to the debate.

Hopefully at some point someone will publish a sensitivity analysis comparing CFE and PCA that shows to what extent the numerical differences are relevant for the final factor scores (which would be a trivial exercise if CFE was implemented in the pkg!).

**Comment by maxheld83** [comment]
Agreed. It would be nice.
However, I see an additional challenge: according to Brown, much of the value of CFA lies in the *manual* **reflection** (this is prior to / not to be confused with *rotation*). 
I have no idea, however, how that would be implemented in pretty much *any* computer program. 
I am not sure whether people have ever done this (tedious) task ever since the PC arrived, but I might be wrong, maybe `PQMethod` has such a facility.

**Comment by bobbraswell** [comment]
I have implemented centroid factor analysis in R and tested it on three data sets. It is ready for further testing.  It has not yet been wrapped in or made flow-compatible with the rest of this project. I'm not sure of the protocol of contributing it at its current stage. Should I make a pull request?

I have in mind a separate cookbook for "old school" centroid + manual rotation. Thoughts?

**Comment by maxheld83** [comment]
That's great news @bobbraswell, we've been hoping for this for some time, and I think @aiorazabala and I both agree that this is a top priority for the package (after manual rotation #13). 

I've opened a new "Milestone" (`1.5.0`) for Centroid Factor Analysis (and associated "Old School" methods), to which both issues (such as this), and pull requests can be assigned.
I imagine that this will take a while, so it probably won't make it to `1.4.0` (which is already crammed).

I think adding it as a pull request would be great @bobbraswell, so we can all look at your work (I'm very curious).
(Pull requests get automatically updated if the fork branches from which they stem are pushed, so the PR can evolve over time).

As for compatibility with the rest of the project, may I suggest the [guidelines for contributing](https://github.com/aiorazabala/qmethod/blob/master/CONTRIBUTING.md)?

I am not sure about the current state of the centroid factor extraction, so this is a very preliminary list of small tasks (some separate issues) that I imagine might be involved:

- [ ] implement centroid extraction as a *separate* function (I think we're mostly trying to keep @aiorazabala's well-tested original functions untouched – and besides, it might be quite an involved / interactive function) -> #15 (this issue)
- [ ] document the function in `q.centroid.Rd`
- [ ] document the function in a separate, *"old school"*  cookbook alternative -> #225
- [ ] offer the function as an argument to `qmethod()`, the "mother"-function that wraps them all. -> #224 
- [ ] check whether existing functions and plots in the package are applicable
 in a centroid context -> #226
- [ ] validate centroid extraction against Peter Schmolck's `PQMethod -> #227

Seems like a lot of work, I don't know about you guys, but I'm really excited about it :sweat_smile:

Thanks so much for getting the ball rolling and doing this important addition @bobbraswell!

**Comment by aiorazabala** [comment]
This issue has been re-wrapped in #352
