### ISSUE TITLE
allow missing values

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#16]
Regrettably, one of my participants has somehow left one q-sort field empty, and lacks a ranking for one item.
If I keep the participant in the p-set, I get:

```
Error in eigen(r) : infinite or missing values in 'x'
```

I haven't thought this through, but I wonder whether conceptually, there is a way for the PCA and qmethod to deal with such missing values.

**Comment by maxheld83** [comment]
thanks @aiorazabala !

I think I'll put this on the back burner and just *impute* the missing value in my case :smirk:

**Comment by aiorazabala** [comment]
(just for the records) 

The missing values are a hindrance only in the PCA step (it should be easily fixable to allow `NA` through all other equations.

Both `prcomp()` and `princomp()` (pkg `base`) need full data, but `principal()` from `psych` **does** allow missing values.

However, I ignore how `principal()` handles `NA`s. Introducing a dataset with `NA`s into `principal()` gives some results, but introducing a correlation matrix with `NA`s instead, does not (and both work fine and give the same results with datasets that have no missing values).

**Comment by maxheld83** [comment]
also see https://github.com/QWrks/pensieve/issues/201

**Comment by aiorazabala** [comment]
If a Q-sort is missing values, I recommend excluding that Q-sort from the study: the researcher doesn't know where the missing statement would have been sorted, and this would have shifted all other statement to either side of the distribution, hence affecting the values of the full Q-sort
