### ISSUE TITLE
visualization for factor space (3D interactive)

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#161]
The idea here is to have a three-dimensional, interactive (as in: you can rotate it) plot of the factor space, _maybe_ even with the possibility to rotate manually (as per #13)

**Comment by maxheld83** [comment]
I'm not sure this is a priority; seems cool and all, but might not be *that* helpful after all. See discussion in #94

**Comment by maxheld83** [comment]
I've tried some existing packages to accomplish this, but generally, they seem to offer less customizability (such as labels etc) when compared to sth like `ggplot2` and they can be a bit unwieldy by design (X11 window server etc.).

```
data(lipset)
lipset.results <- qmethod(lipset[[1]], nfactors = 3, rotation = "varimax")

# just 3d
library(scatterplot3d)
attach(lipset.results$before$loa)
scatterplot3d(x = f1, y = f2, z = f3)  # this is static
```

![rotplot](https://cloud.githubusercontent.com/assets/5372770/8498639/6a5aacd4-2189-11e5-840b-6c337631c6eb.png)

```

```
library(rgl)
plot3d(f1, f2, f3)
plot3d(wt, disp, mpg, col="red", size=3)  # not clear how to add labels etc.
```

![rlgrotplot](https://cloud.githubusercontent.com/assets/5372770/8498652/98b7508c-2189-11e5-94db-d5edbb1b3dcd.png)

**Comment by maxheld83** [comment]
as @aiorazabala mentioned earlier in #13 , the venerable [`ggobi`](http://www.ggobi.org/) is also a choice (though development seems to have slowed considerably).
I couldn't try it out, it only seems to available for OS X 10.5 (?!).

**Comment by maxheld83** [comment]
uh, much like #173 this seems too much work, for too small a use-case.

Also, having used this for a bit, it's not clear how 3D can still be meaningfully interpreted, let *alone* with extra information (such as scores).

There's also, as of now, no possibility to link this to the actual rotation in `q.rotate()`.

Lastly, this doesn't really apply to that many Q studies: if you have *more* than 3 retained factors (as hopefully, many will), you end up needing the exact same kind of pairwise (tripletwise) rotations here, too.

Human beings, sadly, cannot really comprehend >3d.

**Comment by maxheld83** [comment]
@bobbraswell has just suggested this again in a similar form, so I'm reopening this issue:

> On a related note, the big advantage of R is its graphics capabilities. What you have done on your rotation routine is good and more than I had done, but still less than I hoped to do in the "wrapper" for the hand rotation function. As a preview or perhaps as a suggestion, here is a function that was meant to be called just before the user was asked which pair of factors to rotate:
>
> ```
  qplots <- function (X) {
    pairs(X,xlim=c(-1,1),ylim=c(-1,1),pch=20)
    plot3d(X,xlim=c(-1,1),ylim=c(-1,1),zlim=c(-1,1),pch=20) 
    dev.new()
    plot(X[,1:2],xlim=c(-1,1),ylim=c(-1,1), type = 'n')
    text(X, labels = 1:nrow(X))
  }
  ```
>
> This gives a big picture just before asking the user to zoom in on a particular pair. The plot3d function in particular seems extremely useful. By grabbing and manipulating with the mouse, the user gets a better impression of how the individual sorts are arranged in factor space.

**Comment by maxheld83** [comment]
as in the above, I also initially tinkered with 3d plots, but (for now) decided against it, because

1. the limitation to 3 dimensions seemed, ultimately, just as arbitrary (and necessary) as 2 dimensions
2. 3 dimensions seemed like a little information overload (I might be wrong)
3. I prioritised other plots
4. while *navigating* inside a 3-d plot gives the impression of rotating data, it does not actually do that. (Not sure whether it *would* be possible to grab the angles from the graphics device).

I think that clearly, the graphical interface of manual rotation leaves a *lot* to be desired, and maybe a three-dimensional plot would be a very welcome addition.

In the long run, I have a hunch that it might be more worth while to concentrate our efforts on actually getting a *dedicated* graphics platform on board that allows real-time #172 by-hand rotation, as well as a drag-and-drop kind of interface #176 
Maybe `ggobi` or something along those lines would be a start.

I have looked at a bunch of such options under the `rotation` tag.

**Comment by bobbraswell** [comment]
Max, I don't require you to agree with me or share all my priorities, but I do want you to understand me. In expressing interest in more plots, especially this particular 3d plot, I am building on the argument made recently on the q-method list about understanding and interpreting factor space. 

Remembering that the point of all this analysis is to understand and communicate what the researcher learns about points of view, I contend that letting the computer "simulate understanding" by printing out results that the researcher hasn't actually got his head around is poor practice. I fear that too much automation in the decisions made by computers during analysis makes such poor practice increasingly common practice. The researcher should understand the data--and the understanding is necessarily prior to communicating. 

Thus it bothers me not at all that there is no direct way (yet) to go from a 3d plot to a manual rotation based on the angle from which the researcher chooses to view the plot. The point of the 3d plots is understanding, visualizing the arrangement of points in factor space, prior to worrying about assigning a new projection onto axes. 

For example, manipulating a 3d plot of the first three factors (as if one had a plexiglass cube with embedded points, to look at from all angles and manipulate at will) is exactly the kind of visual information that helps one to decide whether varimax would be a good choice for a particular data set. The answer to the question about whether there is one general factor or evidence of clumpiness ought to be based on as many dimensions as one can visualize, even if it's only three.  That's still a 50% increase over being stuck at two.  ;-)

**Comment by maxheld83** [comment]
@bobbraswell – as has been a repeated experience of mine, I am entirely convinced by your argument!
A 3d plot would be a great addition, I think.

I also agree that there's a risk involved in relying too much on automation, though I'd hope that the new facility for manual rotation *does* require people to really wrap their heads around their data.

Anyway, I should add again, that I in no way presume to know which additions would be helpful (if anyone, that would be @aiorazabala's prerogative), and I think it's a good idea to keep this package open and applicable to a wide range of traditions in and approaches to Q.

I also think that vigorous debate can strengthen everyone's point of view, and, ideally, improve the code :)

**Comment by aiorazabala** [comment]
Great, useful discussion!
