### ISSUE TITLE
choose and compare rotation method

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#181]
users might want to visually inspect different _automatic_ rotation procedures before choosing one.

This could be conveniently done inside `q.rotate()` #13 as a first step.

That way, people can also select their baseline rotation for the by-hand rotation (I find it helpful to start with `varimax`, not `none`.)

Users can then either _continue_ with by-hand rotation, or just accept the automatic result and exit.

**Comment by maxheld83** [comment]
got to be careful here to write the correct rotation method to `brief`

**Comment by aiorazabala** [comment]
Automatic rotation methods can be explored on the go using the GUI #67
