### ISSUE TITLE
make qmethod website

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#189]
might be a  good idea to have a pretty website as an entry point with screen shots, gifs, videos etc. as an entry point.

Github offers a neat built-in website builder (via jekyll) for that, might be easy and good enough for our purposes.

**Comment by aiorazabala** [comment]
Like (just to participate in the issue and keep an eye on it)

**Comment by aiorazabala** [comment]
Wiki moved to github pages http://aiorazabala.github.io/qmethod , which is neat as a standard website
