### ISSUE TITLE
zsc_n can sometimes violate the (forced) distribution

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#196]
During plotting exercises I noticed this:

![missing-item](https://cloud.githubusercontent.com/assets/5372770/8758169/3c6a97fe-2ce1-11e5-89d3-87d2eb5b98db.png)

This is actually *not* a plotting artefact (that's what I initially thought), but it stems from `zsc_n`:

```
> count(testrot$zsc_n$fsc_f3)
    x freq
1  -7    1
2  -6    1
3  -5    2
4  -4    4
5  -3    5
6  -2    9
7  -1   12
8   0   10
9   1   10
10  2    9
11  3    6
12  4    4
13  5    2
14  6    1
15  7    1
> count(testrot$zsc_n$fsc_f2)
    x freq
1  -7    1
2  -6    1
3  -5    2
4  -4    4
5  -3    6
6  -2    9
7  -1   10
8   0   11
9   1   10
10  2    9
11  3    6
12  4    4
13  5    2
14  6    1
15  7    1
> sum(count(testrot$zsc_n$fsc_f2))
[1] 77
> sum(count(testrot$zsc_n$fsc_f3))
[1] 77
```

Notice how the above `fsc_f3` *differs* from the forced distribution.

I've uploaded the complete results object for replication [here](https://dl.dropboxusercontent.com/u/5341489/violatedistro.RData) (will be deleted at some point)
(Notice that this snafu happened on *manually* rotated loadings, so it's currently -- absent #178 -- impossible to reproduce from the raw data).

On to the bug tracking:

```
length(unique(testrot$zsc$zsc_f3))
```

yields

```
[1] 56
```

So, obviously, there are duplicate values in there.

I understand that the below snippet from `qzscores()` is supposed to take care of this, specifically the `else` part:

```
  while (f <= length(floa)) {
    if (length(unique(zsc[,f])) == length(zsc[,f])) {
      zsc_n[,f] <- qscores[rank(zsc[,f])]
    } else {
      zsc_n[,f] <- qscores[rank(zsc[,f])]
      # statements with identical z-score
      izsc <- which(round(rank(zsc[,f])) != rank(zsc[,f]))
      uizsc <- unique(zsc[izsc,f])
      for (g in uizsc) {
        izscn <- which(zsc[,f] == g)
        zsc_n[izscn,f] <- min(zsc_n[izscn,f])
      }
    }
    f <- f+1
  }
```

Unfortunately, I don't quite understand what the lower part does.
Could you have a look at this @aiorazabala and figure out what's going on here?

**Comment by maxheld83** [comment]
may be related to #183 ?

**Comment by maxheld83** [comment]
problem seems to stem from how `zsc_n` are calculated ...

Consider how `f3` in the below (the first one printed) does not follow the forced distribution.

```
> count(testrot$zsc_n$fsc_f3)
    x freq
1  -7    1
2  -6    1
3  -5    2
4  -4    4
5  -3    5
6  -2    9
7  -1   12
8   0   10
9   1   10
10  2    9
11  3    6
12  4    4
13  5    2
14  6    1
15  7    1
> count(testrot$zsc_n$fsc_f2)
    x freq
1  -7    1
2  -6    1
3  -5    2
4  -4    4
5  -3    6
6  -2    9
7  -1   10
8   0   11
9   1   10
10  2    9
11  3    6
12  4    4
13  5    2
14  6    1
15  7    1
> sum(count(testrot$zsc_n$fsc_f2))
[1] 77
> sum(count(testrot$zsc_n$fsc_f3))
[1] 77
```

**Comment by maxheld83** [comment]
seems to me like we might have a somewhat non-trivial problem on our hands here: it *is* possible that two tied items (in their `zsc`) will "*break*" between columns, and in a further (very unlikely) subset, such breaking cannot be avoided.

We then have two solutions, equally unsatisfying:

- we violate the forced distribution (that's what seems to be happening here)
- we stick with the forced distribution, but place items in different columns, even though they have the *exact same* `zsc`.

Both suck.

Again, as I said, I'm too dense to understand what @aiorazabala did in the above `else` part, so maybe this is fixed already.

**Comment by maxheld83** [comment]
I would prefer to stick with the forced distribution (mostly because of plotting needs).

A quite simple solution (that actually takes care of the above problem) might be to use 

```
zsc_n[,f] <- qscores[rank(zsc[,f], ties.method = "first")]
```

in the above. 
That'll break the ties according to the *order* in the dataset (if I'm understanding the docs correctly).

From `help(rank)`:

>  With some values equal (called ‘ties’), the argument ties.method determines the result at the corresponding indices. The "first" method results in a permutation with increasing values at each index set of ties. The "random" method puts these in random order whereas the default, "average", replaces them by their mean, and "max" and "min" replaces them by their maximum and minimum respectively, the latter being the typical sports ranking.

Random is nice, too, but that causes problems for reproducible research.

**Comment by maxheld83** [comment]
I *could* implement the above (couple of lines), but I don't want to futz around in `qzscores()` unless @aiorazabala gives the go-ahead, so I'm assigning this to her and waiting for feedback.

**Comment by bobbraswell** [comment]
I hope this is the right way to comment on this issue. I offer my opinion...

I don't see it as a bug. I think it is better for the analyst to be able to see what ties are doing to the categories than to have the resulting distribution artificially smoothed out and the "imperfections" hidden from the analyst. Using the rule of thumb that a difference of two categories in placement of a statement is usually significant, this could lead to some bad conclusions if a statement was moved half the distance for no reason except to balance the grid. If things are "lumpy", the analyst should be able to see that rather than being misled about it.

**Comment by maxheld83** [comment]
@bobbraswell good point, I think I am convinced that we might want to retain the "lumps".

In that case, this is *still* a bug :bug:, but a bug inside my plotting function `q.scoreplot()`, rather than @aiorazabala's `qzscores()` :smile:.

I'll take care of this then.

Still, I'd like some thoughts from @aiorazabala, whether my diagnosis of (my own :disappointed:) bug is correct.

**Comment by maxheld83** [comment]
so, as originally conceived this is then actually *not* a bug, but it just requires an extension to `q.scoreplot` for free distributions, of which this is a special case. ->234

**Comment by maxheld83** [comment]
even if this is not a bug, I've added documentation to `qzscodes` and `q.scoreplot` just in case anyone else stumbles over this.
