### ISSUE TITLE
make plots readable at any size

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#200]
currently, the font sizes etc get all out of whack if you change the size of the plot.

**Comment by maxheld83** [comment]
barring some clever solution to this question, there really isn't anything to be done on this at this point: http://stackoverflow.com/questions/28835491/automatically-scale-font-size-etc-of-ggplot2-inside-an-rmarkdown-document

**Comment by maxheld83** [comment]
still a problem here https://github.com/QWrks/pensieve/issues/254

**Comment by aiorazabala** [comment]
This is a general problem with plotting in R, worth sorting for common examples, but not for all specific potential cases, which need to be dealt with on a case-by-case basis
