### ISSUE TITLE
apply for mozilla open science scholarship

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#214]
https://www.mozillascience.org/fellows

very genereous, but only available to people based in UK, US, Canada.

**Comment by aiorazabala** [comment]
Hey, great find!
Do you know @maxheld83 when was the deadline for this? I may keep an eye for next year

**Comment by aiorazabala** [comment]
[Neat funding](https://foundation.mozilla.org/en/what-we-fund/awards/), but likely not for something at this level
