### ISSUE TITLE
run q.nfactors if nfactors = NULL in qmethod()

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#221]
this might be a simple addition to make `qmethod()` even easier; if people enter no `nfactor =`, we might run q.nfactors (quietly) behind the curtains with all the options and simple take the highest nfactor that still passes the parallel analysis as `nfactor`.

People who beg to differ can always specify their own nfactor.

Might make it a bit easier to start your analysis if you're new to q, and I think parallel analysis is a defensible starting point.

I could do this in a 4-5 lines of code, but will put this on backburner for now.

**Comment by aiorazabala** [comment]
Great idea, although deciding the number of factors to extract is such a core analytical decision that it'll best to avoid giving the impression that there is a "recommended" analytical way to do it, or to anchor it in some way.
It could mislead people learning Q into undervaluing the importance of this step.
