### ISSUE TITLE
enable alternative extraction methods as an option to qmethod()

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#224]
We might see four options at the end of the day:
- PCA via `psych::principal` (done)
- centroid via #15 
- PAF via #20 (at some point?)
- ML via #317 

There are two questions that arise, which should be discussed and resolved in this issue:
1. **Where to implement**: _Either way_ (except for c) some changes to base function `qmethod()` would be required.
   a) could be done _within_ `qmethod()`, though that might make the wrapper quite large
   b) could be done inside a `q.extract()` function, which `qmethod()` then wraps (I think this would be preferable)
   c) could be done in separate `q.centroid()` etc. functions which mimick `qmethod()` (I think this would be confusing for users)
2. **Where to store call**: The choice made in this argument should also be written in some appropriate place into the resulting `qmethod` object, so that it can be reproduced and called upon by other downstream (plotting) functions.

Either way, whichever extraction method is used, the `qmethod()` results object should be similar as far as possible to avoid downstream complications.

**Comment by aiorazabala** [comment]
Argument 'extraction' added to qmethod(), which currently accepts PCA and centroid. The resulting qmethod object has the relevant information. More extraction methods can be added if needed
