### ISSUE TITLE
add more tests until coverage == 100%!

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#259]
we now have some automated (unit) testing in place as per #89 , and for future features or changes, people should _always_ write tests.

However, there are still a lot of legacy functions in here that are _untested_; that's not great.

Any additional tests would be great.

**Comment by aiorazabala** [comment]
Manual tests for validation on all functions were conducted before publication (many, to ensure all functions returned the same values as PQmethod, for a range of datasets). Given not many new functions or changes to core functions are expected, automatic testing is not needed for the time being.
