### ISSUE TITLE
add test coverage to CI and add badge

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#260]
that'd be neat. Something to strive for.
building on #89

**Comment by maxheld83** [comment]
This is now all ready and prepared, @aiorazabala just needs to sign up/in with her github account over at  https://codecov.io/

Once the pull request #97 is merged, we'll see an updated indicator of the code covered in tests. That'S neat.

**Comment by maxheld83** [comment]
@aiorazabala this should actually work *without* changing anything in the travis file; it's all set up – I think you just need to sign up.

**Comment by aiorazabala** [comment]
Done, let me know if it doesn't work
