### ISSUE TITLE
reconstruct `reorder = TRUE` from `psych::principal` rather than reverse-engineer

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#274]
obviously, reverse-engingeering is bad as in the stop-gap #273 so _if_ William Revelle agrees to add this feature to `psych::principal` that would be preferable.

**Comment by maxheld83** [comment]
Here's the email I just send:

> Dear Prof. Revelle,
>
> Many thanks for the prompt addition of the `rotmat` output to `psych::principal` – this is a great feature, and made my life a lot easier developing for qmethod.
>
> I recently noticed that `psych::principal` reorders the components according to their sum-of-squared loadings (formerly known as Eigenvalues, but no longer once the Principal Components are rotated).
(That is documented behaviour in your package, I had just forgotten about it).
> 
> Would you consider adding an argument (say, `reorder = TRUE`)  to `psych::principal` to en/disable this reordering?
> 
> The reordering causes a bunch of problems for my development of a by-hand rotation function for our package "qmethod" (you're probably not interested in the details).
>
> We can of course reverse-engineer the reordering on our end, but I'd like to avoid that if you're open to this suggestion.
>
> I've also posted a question on CrossValidated concerning the reasons for re-ordering.
>
> Let me know what you think about this.
> 
> Best,
> Max

**Comment by maxheld83** [comment]
there *is* now a better way to do this than is presently done: http://stats.stackexchange.com/questions/169934/should-i-reorder-principal-components-after-rotation/169991

This will also, incidentally, render the homegrown flipping from #268 unnecessary.

**Comment by aiorazabala** [comment]
@maxheld83 can we close this?
