### ISSUE TITLE
accept peters tsv in shiny UI

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#287]
Peter wrote:

> in expectation of new, more modern Q programs I had once implemented a tab-separated data export format in PQMethod (cf. the attached lipset.tsv). It is in the person-rows/items-columns format, which is suited for manual editing, e.g. for deleting or reordering sorts. Your online interface, however, imports csv data only in the items-columns/person-rows direction. Perhaps it's not too much effort for you to offer this import format as an

**Comment by aiorazabala** [comment]
Fixed long ago
