### ISSUE TITLE
clarify correlations between factors

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#29]
[Noori Akhtar-Danesh](http://fhs.mcmaster.ca/ceb/faculty_member_akhtar-danesh.htm) raises a problem about interpreting **correlations between factors**:

> - Whatever method we use in PQMethod, factors are theoretically orthogonal and this can be seen easily using PCA in SPSS.
> - Mathematically all subjects have contribution on each factor but in Q-methodology only those subjects who load significantly on a factor are selected.
> - Therefore, in calculating correlation between any two factors only a few subjects are accounted for which may alter the correlation either positively or negatively.
> - Hence, the size of the correlation should not affect our judgment about the relation between factors as **the observed non-zero correlation is just a spurious not authentic one**.
> (Source: presentation at q conference in 2007)

**Comment by aiorazabala** [comment]
I think this can be closed now (there was some open discussion about it if I remember well).

**Comment by maxheld83** [comment]
yup, doesn't seem like a technical/software problem anyway.
