### ISSUE TITLE
ggplot2 warning: "Non Lab interpolation is deprecated probably"

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#290]
ggplot2 as started throwing the above warning, must clarify/solve this issue

**Comment by omarwagih** [comment]
Keep getting this error message in my package. How to fix?

**Comment by maxheld83** [comment]
@omarwagih are you encountering this issue in using `qmethod`, or generally as part of using `ggplot2`?

Just to be clear, this is the place to log issues with `qmethod` – not `ggplot2` per se.

I haven't tried to fix this warning, but will soon and expect that it'll be easy.

**Comment by omarwagih** [comment]
@maxheld83 This is just general use of ggplot2, which I call from my package https://cran.r-project.org/web/packages/gitter/index.html 

Thanks, looking forward to the fix.

**Comment by maxheld83** [comment]
hehe, ok, so we're in the same boat @omarwagih :smile: stay tuned for a fix (if I manage to fix it).

**Comment by omarwagih** [comment]
Haha, thanks! Not sure why I though this was the ggplot2 repo.

**Comment by maxheld83** [comment]
hasn't come up.
