### ISSUE TITLE
fix qdc lines in q.scoreplot

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#293]
it appears that during the last fix, the orientation of the qdc lines was reversed; need to double-check this quite carefully to make sure the plot is correct.

**Comment by aiorazabala** [comment]
Just a big congratulations for this function @maxheld83 , it works really nicely (including the rescaling of the fonts) and the output is both useful and pretty!

**Comment by maxheld83** [comment]
glad you're finding this helpful @aiorazabala!

Just to give you a heads-up; in a recent version, I had actually accidentally inverted the qdc offset, so the plot was partly wrong – this is now fixed on `array-viz`, as well as my `master`.
