### ISSUE TITLE
In import.q.sorts, make q.set argument optional, for one-language studies

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#303]
I think it's an unnecessary complication that adds to the confusion of using this function.

**Comment by maxheld83** [comment]
yup, *except for one complication*: `import.q.sorts` does a bunch of validation tests, and for that it *does* need the `q.set` (it tests for each Q-sort whether it has all items from the `q.set` and vice versa).

Still, it could be made an optional argument, in which case there would simply be no test of that.

Generally, it might be more preferable to take care of this in a modular fashion, whereby the validation happens in one function, the importing in one, and the multilingual/multicondition in one.

Seems like having too many arguments / special cases for functions makes them too complicated.

I'm just not sure I can pull of the modularizing for `1.4.0` maybe this can wait until a later release.
