### ISSUE TITLE
Improve message error in import.q.sorts

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#310]
In `import.q.sorts()` if the lookup table in `manual.lookup` is longer than it should be (e.g. 40 statements instead of 30), the function throws the following error

``` R
Error in current.sort[current.sort == id] <- handle : 
  replacement has length zero
```

Maybe add a line of code with an error message indicating that the reason for this error is that the `manual.lookup` might be wrong?

**Comment by maxheld83** [comment]
will do!

**Comment by maxheld83** [comment]
duplicate of https://github.com/maxheld83/pensieve/issues/94
