### ISSUE TITLE
q.set in documentation of import.q.sorts

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#312]
In the documentation of `import.q.sorts` where it says:

``` R
    \item{q.set}{
        A matrix with handles as row names, languages (if applicable) 
                in columns, as read in by \code{\link{build.q.set}}.
    }
```

Is it a matrix of full statements with handles as rownames?
Please indicate "a matrix of what", e.g. `A matrix of full statements with handles...`

**Comment by maxheld83** [comment]
duplicate of https://github.com/maxheld83/pensieve/issues/95
