### ISSUE TITLE
qmethod silently accepts arbitrary additional arguments

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#315]
it appears that `qmethod()` will just accept an arbitrary additional argument like `method = "ml"`, which might raise the expectations for some users that something would be _done_ with this argument (though that is not the case).

I am not sure what the recommended way for dealing with additional arguments is in R packages, and (related), if we're passing on such arguments to other functions.

Anyway, might look into this to make the package more robust.

**Comment by aiorazabala** [comment]
This behaviour occurs with many of the standard R functions, e.g.:
`t.test(c(1:10), method="ole")`
This code gives no error, and yields the same output as:
`t.test(c(1:10))`
So the behaviour of `qmethod` is consistent with other main R functions, and there is no need to address this IMHO.
