### ISSUE TITLE
document ideal file structure for import

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#32]
I've spend some time figuring out how to best save, version-control etc. all the stuff that goes *into* a q study, including `sample`, `concourse`, `sorts` etc.
I keep repeating myself in documenting this in individual functions, so I should probably put this in *one* place somewhere.

**Comment by maxheld83** [comment]
Several options come to mind:

- a page on the wiki
- a section in `qmethod-package.rd`
- a new `*.Rd` for some to-be-included example dataset (though I am not sure if it's acceptable/advisable to include a *directory structure*, rather than an `*.rda` as an example ... . An `*.rda`, obviously, would not make sense.

Any thoughts, @aiorazabala ?

**Comment by aiorazabala** [comment]
Not sure if I understand your question, these objects would be data, Correct? Do you mean the specific data of a study? (i so, then it should be *.Rdata)

**Comment by maxheld83** [comment]
no, the *example* objects would have to be a directory structure with some `*.csv`s and `*.tex`s, so people can see what kind of structure works and is expected, by say, `import.q.concourse`.
(I am trying to keep these functions as generic as possible, obviously, so that people can adapt them to their own needs).

I'm not even sure such an example data structure is necessary, maybe I can just write it up somewhere – I am just wondering where the best place might be.

Maybe I'm overthinking this.

Here's the data structure I came up with: https://github.com/maxheld83/keyneson
- Notice the nested git submodules; they allow neatly independent versioning, of, say, the concourse and the sample. Different studies can draw different samples from the same concourse etc. etc.
- (Ignore the submodule-ed `.wikis`, these are for documentation)

**Comment by aiorazabala** [comment]
Thank you, I see. 
It depends very much on what you want the data for, if it is to illustrate an import function from CSV/TXT, then it can perfectly go within the folder 'data' in the package, as such file. 

If you just need to demonstrate what structure is needed to input into the function, an rda would suffice (e.g. data(lipset) ).

You can also use the lipset dataset for illustration purposes, for example, you can add a third or subsequent objects to the lipset list (data/lipset.rda), in which you include the concourse, separate qsorts, etc.

**Comment by maxheld83** [comment]
I'll document this on the wiki asap, as discussed.

**Comment by maxheld83** [comment]
I asked on StackExchange how to best ship a directory of CSVs with a package, without upsetting CRAN -> http://stackoverflow.com/questions/28116448/ship-directory-of-csvs-with-r-package?stw=2

**Comment by maxheld83** [comment]
first draft is done.
Check out https://github.com/aiorazabala/qmethod/wiki/Data-management if you're curious @aiorazabala 

I hope I got the tone right; these are of course merely suggestions, and they don't apply to everyone.

I hope I managed to explain some of the rationale for this complexity.
I wonder whether concourse theory may not in fact require us to make sure that q method is done in a cumulative, systematic way. 
Maybe I'll sit down and write an article on that for Operant Subjectivity one day, would need to read some more Stephenson first :).

**Comment by aiorazabala** [comment]
Sounds good! I particularly like the emphasis on reproducibility etc (we're teaching this 'Replication' course which is all about reproducibility http://nicolejanz.de/teaching/replication.html)

As I understand, one would keep each statement in a separate csv file? I'd still see more natural to use a csv table for all statements (or for the whole concourse) rather than multiple small files, but that's a question of taste.

Also, check out the format of results that FlashQ provides as raw: http://az296.user.srcf.net/FlashQ/data/Q_method_course_Learner_Preferences_1_0.csv perhaps something to consider in the future in order to adapt them to your functions?

Actually, I'd need to adapt import.q to that format as well... #50

**Comment by maxheld83** [comment]
Great :smile: – I'm glad you like it.
Reproducible research is definitely important.

Re: **separate files** : 

For the concourse, statements are expected in individual `.tex` files, not ~~`.csv`~~.
The rationale behind individual files was the following:

1. Since crafting items is hard (and hopefully a collaborative effort), I wanted the entry to be as lightweight as possible, hence preferably *without* using a spreadsheet editor.
2. As in my case [`keyneson`](https://github.com/maxheld83/keyneson), full item wording can sometimes be quite long, and involve some amount of formatting, non-ASCII, etc. – all of which seemed easier in a `.tex`, than as a column in a `.csv` with line wrap enabled.
3. I have this dream that *several* people collaborate on a concourse. If the entire concourse sits in *a* `.csv`, the sort of rows would screw up the versioning (and `git diff`s).
  With individual `*.tex`, sorting does not matter one bit.

Does that make sense?


Re: **FlashQ**:
That's a good suggestion, thanks @aiorazabala . I understand you might add the raw data in #50 that would leave concourse, q set for me -> #53
I'm not sure I'll get to that soon though; I'm not sure about:
a) the value of Flash as a platform, looking towards the future (compared, to, say shiny?)
b) the concept validity of Q sorts on screens, especially online (that would seem to require *huge* screens).

**Comment by VerenaKasztantowicz** [comment]
Great [explanation](https://github.com/aiorazabala/qmethod.wiki.git), helps a lot at the beginning to organize the directory. + I like the connection to concourse theory.

**Comment by maxheld83** [comment]
I think this can be closed for now, since it is on the wiki.
