### ISSUE TITLE
add duplex option to make.cards

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#328]
`make.cards()` is best printed on *both* sides, so that you have the stimulus on front, and ID/handle on the back.

Some printers support duplex printing, and for that purpose, it would be very helpful to be able to export PDFs where every page was rendered twice, because printer drivers usually do not support this kind of thing. 
(you can enter n of copies, but that'll be printed *after* the first batch).

Not sure how to implement this:
- either in LaTeX (if there is such an option as repeat page, unlikely)
- in R / xtable, just repeating the respective rows twice, though that would depend on the type of template (maybe hard code the n of cards / page per template into `make.cards.R`.)
  - so this would basically be some simple function that repeats some subset of rows *twice*, where the number of rows depends on the template (ie. how many rows fit on a template, which would have to be hard-coded dependending on the template somewhere in `make.cards()`

Would make printing on duplex a *lot* easier.

@VerenaKasztantowicz maybe you want to look into this, since this will be especially handy for image-sorts?

**Comment by VerenaKasztantowicz** [comment]
+1 That would be nice as a new argument in R... I'm thinking about it.

**Comment by maxheld83** [comment]
@VerenaKasztantowicz can you try this out, too? It's in the `make-cards-conveniences` branch.
Will merge it if it works for you, too.

**Comment by VerenaKasztantowicz** [comment]
It's working @maxheld83 thx

**Comment by maxheld83** [comment]
great, done :)
