### ISSUE TITLE
significance levels / stars in qdc

### ISSUE THREAD

**Issue by r3xth0r** [aiorazabala/qmethod#362]
The flagging of significance levels as provided by `qdc()` seems to be wrong for the 4-star significance level, which in its current implementation flags at a significance of 0.000002 and not 0.000001 as implied by the code.

    sedth.000001 <- sed[first, second] * 4.753
    sedth.001 <- sed[first, second] * 3.291
    sedth.01 <- sed[first, second] * 2.576
    sedth.05 <- sed[first, second] * 1.96

While the first three quantiles are specified correctly, the 4.753 quantile does refer to the one-sided variant:

    > round((1 - pnorm(c(1.96, 2.576, 3.291), mean = 0, sd = 1)) * 2, 3)
    [1] 0.050 0.010 0.001
    > round((1 - pnorm(4.753, mean = 0, sd = 1)) * 2, 6)
    [1] 2e-06

The correct quantile for the two-sided variant is

    > qnorm(p = 0.000001) %>% round(4)
    [1] -4.8916

It would be nice to specifically include the meaning of the 3 and 4 stars flagging to the documentation of `qdc {qmethod}`; looking up the meaning of the 4-star significance level was why I noticed this in the first place.

**Comment by aiorazabala** [comment]
Many thanks @r3xth0r for spotting this and for giving a solution. 

The full details of significance are now in the documentation of `qdc()`. I've changed the `"****"` with `"6*"` to make it more logical. I've also fixed the value for a p-value >0.00001 (from 4.753 to 4.8916, `qdc.R`, line 31).

As indicated in #360 in Q only the first two (0.05 and 0.01) are typically used (PQmethod does't look beyond), and the distinguishing/ consensus statements also are based on the higher p-values. 

The reason why a test for p-value > 0.000001 was included is that, while testing, I was curious about some data that appeared to yield very high significance, and so I included that test to see to how far it'd be significant. But for most uses, this is not relevant.

The values for 0.05, 0.01 and 0.001 are taken from Brown, 1980, pp.245. The value for 0.000001 was mistakenly taken from `qnorm(0.000001)`.
