### ISSUE TITLE
qmethod only works up to 9 factors

### ISSUE THREAD

**Issue by JonasGeschke** [aiorazabala/qmethod#363]
Hallo, I actually run a very basic testing code with random data of 100 Q sorts with 17 statements. Up to 9 factors, the analysis works well. From 10 factors on, I get the following error message:

> Error in Ops.data.frame(zsc[first], zsc[second]) : 
>   ‘-’ only defined for equally-sized data frames

Does qmethod generally function with up to 9 factors only? As I cannot really think of a reason why this should be the case, I would be happy about help sorting out this error... thanks!

**Comment by JonasGeschke** [comment]
@aiorazabala can you approve the pull request #361 ?

**Comment by aiorazabala** [comment]
Done, sorry for the delay. It'll go to CRAN in the next version release (likely in a few months, with few more improvements)
