### ISSUE TITLE
Missing warning message with negative loadings

### ISSUE THREAD

**Issue by LaraSp** [aiorazabala/qmethod#383]
Hi,

I wanted to tell you about a case that happened to me analyzing my data with the package, in case it is useful. I don't have much idea of using GITHub and I'm very new with this kind of analysis, I hope this is the right channel and that the comment is useful. 
Analyzing my data (94US and 30 Statements) and using PCA and varimax automatic rotation, I have selected 5 factors (following the criteria of minimum number of Q-sorts at least 2 in each factor and Humphrey's rule). When I reviewed the Q-sort assigned to each factor I realized that for discourse 5  there is a Q-sort completely opposite to the idealized Q generated. This comes from the fact that the factor loading of this Q-sort is significant but negative (-0.48*), reviewing the documentation of the package I have seen that the qflag function (if I understood correctly) should send a warning message in these cases "The function also runs two checks: Q-sorts flagged that have negative loadings and Q-sorts flagged in more than one factor. If any of these is true, the function returns a warning for the user to inspect the automatic pre-flagging (which should be done in all cases, but particularly in these ones)", but it has not been the case. I warn you in case there is something missing in the package that should send the warning but doesn't do it, or something else. I also wanted to ask, if possible, if you can advise me what to do in this case, switch to manual rotation with the advanced analysis option that I have seen in the cookbook? I have not found much information on what to do in these cases.

Best regards!

**Comment by aiorazabala** [comment]
Dear Lara,
Thank you for your message, and my apologies for the delay in responding. Feel free to email me directly for faster response (aiora.zabala@gmail.com).
The lack of such warning message is likely because the latest version of the "qmethod" package was not being used.
If you want to manually change the flags, you can see instructions here http://aiorazabala.github.io/qmethod/Advanced-analysis
With best wishes,
Aiora
