### ISSUE TITLE
define q-sort distribution automatically

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#4]
We should have a function that automatically calculates a q-sort distribution (during study design), using the following parameters:

- [ ] number of statements/items
- [ ] maximum Q value (say, `+5`)

This is a lot less than it used to be, but these are the essential ones and they will be meaningful to most users, I think.

**Comment by maxheld83** [comment]
I'm trying to do this now, but haven't gotten far.
I'm wondering – can this also be accomplished with the density function `dnorm`, without drawing random samples?

**Comment by maxheld83** [comment]
ok, I think I'll split this out into different issues, with this being only the basic functionality (see above).

Additional features include:

- arbitrary skew -> #57
- arbitrary distribution -> #58
- arbitrary kurtosis -> #59

**Comment by maxheld83** [comment]
so just to clarify, the work on this issue now lives in the cleaned, open #61

**Comment by maxheld83** [comment]
yikes, that first draft was bad.
Should be better now, with [help](http://stackoverflow.com/questions/28221280/generate-normal-distribution-with-exactly-n-elements-in-y-bins) from StackExchange.

As expected though, `make.distribution` won't always hit the specified `nstat` exactly, because of rounding errors.

I'm guessing this isn't a programming artefact, but real: not *every* `nstat` will fit comfortably into `max.bins`.

I'll add doc to that effect and through a warning in case `nstat` isn't hit exactly.

**Comment by maxheld83** [comment]
I've now added documentation + warning message for `nstat != sum(distribution)` in 6b28a3ce1aa317a29fec6a60ca3025b01fa424b7

I'm not sure what to do about this:

- It may be quite annoying to the user, if they don't get the `nstat` they entered.
- On the other hand, strictly adhering to a standard normal distribution would seem to imply that *some* combinations of `nstat` and `max.bin` just aren't that great.

**Comment by VerenaKasztantowicz** [comment]
+1

**Comment by maxheld83** [comment]
this is done now, awaiting merge in #61
