### ISSUE TITLE
apply documentation conventions to import/export functions

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#43]
Lets decide on a convention to refer to 'Q' in Q-sorts, Q studies etc.
My preference is to use capital Q in all cases, and separated either by a space (e.g. Q studies, rather than qstudies) or by a - (e.g. Q-sorts).

Also to refer to file formats: lets do either TEX or *.tex consistently, but not both, and preferably not csvs (but rather CSV / *.csv files, check e.g. documentation for import.q.feedback)

id with capitals (ID)?

**Comment by maxheld83** [comment]
Thanks for the review, and sorry about this kind of inconsistency.

I agree, and I'll fix those asap and send along a new pull request.

- [ ] Q sorts (etc.)
- [ ] ID (capitalized)
- [ ] `*.csv`

**Comment by maxheld83** [comment]
edit to the above: I see @aiorazabala has so far used CSV (not `*.csv` or something) to identify file name extensions, so I'll be doing the same.

**Comment by maxheld83** [comment]
hope I got them all; really, my conventions were quite the mess.
Will send along pull request later along with other fixes.

**Comment by maxheld83** [comment]
ok, I think this is done.
