### ISSUE TITLE
better document import/export functions with examples

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#44]
I'd suggest the following review in the documentation, before submitting the new functions to CRAN:
- [x] Spot and fix unfinished statements (e.g. 'Note' section in `make.cards`)
- [x] See also the 'documentation conventions' issue #43 , to make the documentation more consistent
- [x] When referring to arguments and argument values in the documentation, use the code formatting (e.g. `q.distribution` in 'Notes' of `build.q.set`), the markup is, e.g. `defaults to \code{"varimax"}`
- [x] I couldn't understand 'short handles', do they refer to a sort of statement ID?

If possible, please add **examples** of usage, otherwise it is really hard to understand what sort of objects are needed as inputs (I couldn't really try any of the functions for that reason, and I would love to see what they do)---essential for people to use your functions!
You can add further objects to the list of the `lipset` data. For example, the `q.sample` for `build.q.set` could be `data(lipset); lipset[[2]]`, and for q.distribution, add a third object to the `lipset` data, e.g. `lipset[[3]]` with the array of the distribution values:
```{r}
lipset[[3]] <- sort(lipset[[1]][,1], decreasing=FALSE)
```
...or simply add a data example of yours to the `/data` folder

**Comment by maxheld83** [comment]
and thanks again: I'm on it.

- I think I'll go with a data example of my own then, with a bunch of `*.csv` in folders, also as per #32 

About the short handles: These functions use **two** ways to refer to full items, 
1. (meaningless) **ID**s (`c132`) and 
2. (meaningful) short **handles** (`growth-trumps-equality`), and then there's the 
3. **full item** (`Growth is more important than ...`).

I know this is a tad bit confusing, and I kept going back and forth with naming.

What makes sense to you, @aiorazabala ? **ID**, **handle** and **full item**?

To make matters worse, IDs can be either hard-entered, or automatically created as hashes, but I both call them ID, because they serve the same purposes and most of the functions don't care how some ID was entered. 
Makes sense?

**Comment by maxheld83** [comment]
I'll go about the **examples** in several steps:

- [ ] add my [keyneson](https://github.com/maxheld83/keyneson) data as an example structure to the `/data` folder, hopefully this won't cause errors.
- [ ] add a section to `qmethod-package.Rd` explaining the ways by which items are referred to:
  1. full item **wording**
  2. item **handle** (short, but meaningful to the researcher)
  3. item **ID** (short, meaningless for humans)
- [ ] add a section to `qmethod-package.Rd` explaining the nested data structure of `sorts/sample/concourse` directories
- [ ] draft a more fleshed-out version of tips for a good data structure as part of the wiki #32 
- [ ] point users of the import/export functions to the general information in `qmethod-package.Rd`
- [ ] point users of the import/export functions to the fleshed out argument in the wiki

**Comment by maxheld83** [comment]
ok, that was a piece of work so far.
I ended up not using (my) keyneson datasat, but a synthetic stupid example, just because keyneson turned out to be much, much too complicated and caused too many errors.
Let's not do any more file system operations anytime soon :/ documenting them is such a pain (non-asci errors, missing object errors, ...).

Anyway, I hope this is ok for now.

I still have to write the wiki page, and then I'll send along a PR.

**Comment by aiorazabala** [comment]
Yeah, you can imagine how laborious it was to test, re-test, validate, and validate again the existing functions too. 

Please make sure that you thoroughly test the functions, validate and add statements to check for input errors, and make sure that the documentation is clear enough; an educated user should be able to understand what the function does and what are the inputs, and able to try the function, and examples are best where the input is not obvious from the documentation (no matter how simple they are).

The idea of the package is for other users to be able to use your functions, so these need be not too specific to your study plan, and need to be sufficiently documented. This is not required by CRAN, it is just to keep the package a good quality package, and ultimately for other people to use it and avoid frustration due to lack of clarity (sorry, I've been teaching R too much and I've seen much of that frustration, hence my emphasis on making the documentation and usability clear).

**Comment by maxheld83** [comment]
Wow, yes, I am beginning to imagine the incredible amount of work and care you put into `qmethod`, @aiorazabala . Quite humbling, really.

Thanks for reminding me that functions should be generally applicable – and not overly specific to some study agenda. I lost track of that. I think I've cut down on most of the special cases as per #45, and will still get rid of the multilingual default as in #46. 

These are the kinds of I've so far always done (and passed) for my additions:
- [x] `R CMD Check`
- [x] Error out with meaningful messages (the import functions implement a number of tests for consistency) or give warning message.
- [x] Documentation and example is now, hopefully, in a better place (still in my fork, PR to come)

I'm not sure what you mean by 
> validate and add statements to check for input errors

Something like [this](http://stackoverflow.com/questions/19363827/validating-input-to-a-function-in-r)?
Could you give me an example of what would be required here?

I obviously still have a lot to learn – hope these additions are worth your trouble!

**Comment by aiorazabala** [comment]
Yup, like tin the example.

See also, e.g. qmethod() line 10. These input checks are recommended so that, when the user doesn't obtain what they should (due to a mistaken input), or gets an error, the function warns, or stops or gives an indication of what is (might be) wrong. Usually just for incorrect data classes, or incorrect dimensions of the input etc.

**Comment by maxheld83** [comment]
thanks @aiorazabala !
I think I have some of those, but let me go through the functions systematically again and check.
new issue -> #49
