### ISSUE TITLE
reduce arguments in import/export functions

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#45]
Two suggestions to improve the usability in terms of arguments (Perhaps this should go to the README-contribution later on?).

ONE. As a general principle, I suggest to set up the arguments so that the user has to input only the necessary ones. Give as much as possible by default, and only the essentials have to be specified (to make it easier to use; I got that feedback from reviewers from the R Journal).

For example, if the argument can only take one value at the moment, then specify so in the 'Usage' and the R function, e.g. 
```{r}
# currently:
make.cards(q.set, study.language, paper.format, output.pdf, manual.lookup)
# to be transformed into:
make.cards(q.set, study.language, paper.format="AveryZweckformC32010", 
                   output.pdf, manual.lookup)
```
Or simply eliminate that argument for the time being (and add it as an argument when there are more options). Later on, when there are more formats available, change it to an array, where the first element will be the default:
```{r}
make.cards(q.set, study.language, 
                   paper.format=c("AveryZweckformC32010", "A4", "Letter"), 
                   output.pdf, manual.lookup)
#see an example in:
?cor # argument 'method'.
```

Another example: `study.language` could have a default value, or a set of values (either the number of the column where the statements are, or `English`/`Deusch`, or whatever convention...). The idea is that, if my study has a single language, it would sound unnecessary to have to specify the language. The code would look like:
```{r}
make.cards(q.set, study.language="default value here", 
                   paper.format, output.pdf, manual.lookup)
```

TWO. If there is a default value, this should be clear in the usage, e.g. in `make.cards`, argument `manual.lookup` indicates that the default value is `NULL`, then the 'Usage' and the R function should read:
```{r}
make.cards(q.set, study.language, paper.format, output.pdf, manual.lookup=NULL)
```

**Comment by maxheld83** [comment]
again, thanks so much for the feedback – I had a hunch there would be room for improvement.
I'll fix it and report back here.

**Comment by maxheld83** [comment]
I'd like to spin out the `languages` stuff into a new issue, because it turns out to be a bit more complicated than expected -> #46
