### ISSUE TITLE
support one-language studies (make multilingual optional)

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#46]
@aiorazabala suggested (convincingly) in #45 to reduce the number of necessary arguments to a minimum in any given function.
`languages` is one of those arguments, that make sense only for a (minority) of studies, so maybe the import/export functions should be built so as to make this optional.

**Comment by maxheld83** [comment]
If I am not mistaken, only `import.q.concourse.R` actually calls for users to specify the language(s) of their study – all other functions read it in from the resulting `q.set`s. 
(Naturally, `make.cards` also requires this `study.langauge` as an argument, too, to print out the appropriate language version).

I generally agree that this (multilingual) studies is a relatively rare case, although – arguably – more people *should* translate their items into english for reproduceability and international accessibility.

I see a couple of reasons for keeping in `languages` as an argument, with *no* defaults:

1. the necessary changes to `import.q.concourse` would not be entirely trivial, because both the actual reading in of CSVs (in their paths) and the warning messages (as details) require a language as of now, would need an additional `if () {}` thing I guess.
2. the function works fine if people just specify one language (`english`) and name their concourse file accordingly – even though this will admittedly be counterintuitive.
3. *if* `languages` has a default, or becomes optional, we need to document and expect two slightly different file structures, as is already the case for `conditions` (which *is* optional) – I fear this may add its own layer of complexity for users.
4. I have this dream where really, different researchers collaborate on the *same* concourses, and really make Q methodology a cumulative research project (which seems to me to be in line with Stephenson's idea of a concourse). For that to happen, we may quickly run into situations where some project (concourse) now *wants* a translation. Switching from a one-language to a multilingual project and file structure then becomes a little complicated.

On balance, it seems to me that the additional hassle of specifying a language in a one-language study are outweighted by the complexity of supporting both one- and multilingual studies, so I'd prefer to keep this in, at least for now.

I will add an additional line in the documentation, advising people with one-language studies.

Does this make sense @aiorazabala or am I just too obsessed about multilingual studies?

Ps.: I *will* implement all the other defaults in #45

**Comment by maxheld83** [comment]
there's now a default language `"english"` in all relevant functions.
If you think that'll do for simplicity @aiorazabala, feel free to close the issue, otherwise I'd suggest we put it on backlog.
Or would this be something that might make CRAN reject the whole thing?

**Comment by aiorazabala** [comment]
No. This is no reason for CRAN to reject it. CRAN only rejects code that gives errors. It's only for usability, i.e. I wouldn't use a function that requires me to specify unnecessary things if I can instead just import a CSV of the statements. So perhaps the function could be named specifically for what it is: import.multilingual.concourse or smthg like this.

**Comment by maxheld83** [comment]
makes sense.
Eh, screw it, I'll hack sth together to make language optional, as you originally suggested.
Something like `import.multilingual.concourse` seems a little inelegant to me.
