### ISSUE TITLE
get DOI for qmethod (via zenodo)

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#47]
There's a neat integration with DOI provider zenodo that automatically creates bibliographic records for github repositories, including ones with code.
It also automatically creates a new one, if there is a new release.

https://guides.github.com/activities/citable-code/

@aiorazabala maybe something for you to check out? Or maybe it just duplicates the CRAN practices ...

**Comment by aiorazabala** [comment]
working on it...

**Comment by aiorazabala** [comment]
Done
[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.593190.svg)](https://doi.org/10.5281/zenodo.593190)
