### ISSUE TITLE
add input validation to import/export functions

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#49]
@aiorazabala in #44 :

> Please make sure that you thoroughly test the functions, validate and add statements to check for input errors, and make sure that the documentation is clear enough;

This exists for some cases, but @maxheld83 should go through all import/export functions again to check systematically.

**Comment by maxheld** [comment]
Hi aiorazabala,

I think you are tagging the wrong maxheld here, I keep getting notifications for this project. I think you mean maxheld83.

Many thanks,
Max

**Comment by maxheld83** [comment]
darn, sorry about that @maxheld 
That was my mistake.

**Comment by maxheld** [comment]
No problem @maxheld83
Nevertheless, it's nice to meet someone with the same name!
