### ISSUE TITLE
build function(s) for sampling of q-items into qmethod

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#5]
There should be functions that allow both:

- [x] Structured sampling, drawing theory-driven samples from a concourse based on some sampling structure
- [ ] Random sampling, drawing items from a concourse based on some randomization. -> #86

**Comment by maxheld83** [comment]
the current versions (and what I'll be able to ship anytime soon) of `build.q.set.R` actually don't *draw* a sample, but merely subset a concourse based on a given sample.
So this isn't done yet.

**Comment by maxheld83** [comment]
dine in #40

**Comment by VerenaKasztantowicz** [comment]
I cloned your [fork](https://github.com/maxheld83/qmethod.git)@maxheld83. it worked fine. Thank's!

**Comment by maxheld83** [comment]
should probably stay open until PR #52 is good and merged.
