### ISSUE TITLE
Import Q raw data from other formats

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#50]
As per the title, see example of FlashQ results here: http://az296.user.srcf.net/FlashQ/data/Q_method_course_Learner_Preferences_1_0.csv

Options:

a) Change `import.pqmethod()` into `import.qm`, with an argument to specify `source=c("PQmethod", "FlashQ")`
b) create a new function `import.FlashQ`

**Comment by aiorazabala** [comment]
Add support for HTML5

**Comment by aiorazabala** [comment]
Fantastic. The formats to import that I have in mind are:
- [X] PQMethod (single LIS file), in function `import.pqmethod()`
- [ ] FlashQ (single CSV file)
- [ ] HTMLQ (?)
- [ ] Q-Assessor (?) Details in #117 

These import functions should be very simple to code. They're planned already in issue #50 . The idea is to create a function for each of them (or a single function `import.q()`, with argument `format=c("PQMethod", "FlashQ", "HTMLQ", "Q-Assessor")` --What do you think would be best?). Then this (these) simple function(s) could be called from within your import functions.

I'm waiting for response from Johannes O to see how the data file looks like out of HTMLQ.

**Comment by maxheld83** [comment]
agreed, separate functions make perfect sense.

**Comment by aiorazabala** [comment]
New function created, `import.html5()`, which imports data from both HTML5 and FlashQ --- both output data with the same structure and format.

**Comment by aiorazabala** [comment]
I emailed Stan Kaufman and there's no need to make a function to import from Q-Assessor. That software does not have a native data format, but just exports data into other formats as an additional feature. It already exports in the PQMethod format, which can be read with `import.pqmethod()`.

**Comment by maxheld83** [comment]
fantastic, thanks for carrying this through.
