### ISSUE TITLE
import concourse, handles from FlashQ and HTMLQ

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#53]
I'd be nice if `import.q.concourse`, `build.q.set` etc. could also import stuff from [Flash Q](http://www.hackert.biz/flashq/home/).

We need import wrappers/options for:
- ~ [ ] concourse~ (there is no concourse in HTMLQ by default)
- [ ] q set

The importing of q-sorts is already covered in #50, I think.

**Comment by aiorazabala** [comment]
The importing of q-sorts is already covered in #50, I think.
YES

**Comment by maxheld83** [comment]
also from the [HTML5](https://github.com/aproxima/htmlq) package

**Comment by aiorazabala** [comment]
Updated in #370
