### ISSUE TITLE
build (LaTeX) template that prints q-cards

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#6]
Build q-cards from the qsample (as per #5) and render them into a nice, printable, latex/knitr/xtable table.

Maybe with variable geometry as arguments, or for standard business cards (same size everywhere).

**Comment by maxheld83** [comment]
done in #40

**Comment by VerenaKasztantowicz** [comment]
thank you, @maxheld83 . For my first qstudy I needed 30 sets with 61 items ...with business cards it couldn't be easier. 
![items duplex](https://cloud.githubusercontent.com/assets/6077855/6124287/75978344-b10c-11e4-8646-af43f47c5551.jpg)

**Comment by maxheld83** [comment]
looks great @VerenaKasztantowicz ! Glad this helped and worked out.
Looks like the margins weren't completely symmetrical, though – might be because of the bigger font size.

**Comment by maxheld83** [comment]
should probably stay open until PR #52 is good and merged.
