### ISSUE TITLE
calculate standard deviation per item per factor

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#66]
I'm working on a visualization of the q factor array (#14), where I'd like to use the standard deviation of each item among the flagged sorts of a given factor.
So for item `feel-good`, I'd like to know how much that *actually* spreads among the people who where flagged for factors 1, 2, etc. – for every item. (I'd also weigh this according to the loadings).

This will probably overlap with the `qdc.R` results (because highly dispersed items are unlikely to be consensus or distinguishing vis-a-vis other factors), and it also tends a little towards R methodology and may therefore be controversial.

I'd still like to have this for a visualization, so that you have an immediate impression on which items in any given factor array where really placed tightly around that location.

I'd like to offer this is an additional output created by qmethod, defaulting (of course) to `FALSE`.

It seems like `qzscores.R` might be a good place to do this, because it also returns all the other stuff and already has the weighted, flagged dataset in place with `wraw_all.

Shouldn't be more than a couple of lines.

**Comment by maxheld83** [comment]
@aiorazabala can you weigh in if you have a chance?

**Comment by maxheld83** [comment]
I've added a little early draft of the visualization to #14 to explain what all the fuss is about.

**Comment by aiorazabala** [comment]
Please, add this additional calculation as a new function, but not in qzscores()

For clarity, lets leave qmethod() and qzscores() for the essential analysis (what is given in PQMethod and what is explained in Brown 1980).

Any additional thing to go as separate functions, that can be applied to an object of class "Qmethodres".

As recommended by the R package gurus, it's better to have many small functions than one that does too many things. And this will also help us avoid introducing errors in the basic functions (or having to re-re-retest these functions again).

**Comment by maxheld83** [comment]
uh ok, that makes sense.
I'll do that and update my pull request #75 as soon as I can (might be a couple of days).

My problem was that I wanted to reuse as much of `qzscores` (especially the flagging and weighing) for the calculation of `item-sd`s, to avoid mistakes and to keep everything tight and elegant.
Could you point me to a better way to re-use the code in `qzscores`, without actually polluting it with this new function @aiorazabala? Can I just `source()` it in another function?

> Any additional thing to go as separate functions, that can be applied to an object of class "Qmethodres".

I also have to read up on the treatment of classed objects.
Could you point me to a resource about this @aiorazabala ?
This would also apply to the entire `array.viz` function (#14), I guess, as well as to making `item-sd`.

**Comment by aiorazabala** [comment]
To create a function that requires a specific type of class (a new function, not a generic function such as print or plot), a simple approach is to add a validation line of code at the beginning of the body of the function, e.g.

```{r}
myfuction <- function(x){
if (class(x) != "QmethodRes") stop("The inputs needs to be an object of class...")
...
}
```

**Comment by maxheld83** [comment]
Makes sense, thanks so much for the pointers @aiorazabala .
I'll get to that and update the PR accordingly once done.

**Comment by maxheld83** [comment]
@aiorazabala:
>  However, perhaps the simplest is to run qmethod() or qzscores() in full, obtain the results, and then run your additional calculations over the object of results (much like the functions plot and print do for an object of class "QmethodRes").

That's the route I decided to take, except that I don't run `qmethod()` again, but simply expect it's results as an input (checking for the class) – that seems safer, because the additional information provided by this new `q.item.sd()` really always relates to a *particular* Q analysis.

**Comment by maxheld83** [comment]
@aiorazabala 
>  If necessary, we can separate the weighing code into a new little function;

I think it might be necessary, and that's what I'm proposing in #129 . See #129 for more discussion.

**Comment by maxheld83** [comment]
this is done now, awaiting last revisions and corrections before merge in #97
