### ISSUE TITLE
GUI - simple visual interface for 'qmethod'

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#67]
In the making with shiny!

**Comment by maxheld83** [comment]
wow, that's great!

**Comment by aiorazabala** [comment]
work in progress https://azabala.shinyapps.io/qmethod-gui/

**Comment by maxheld83** [comment]
wow. That looks fantastic, I can see how this will be *very* attractive to people, it just makes it so simply to play around with different combinations.

**Comment by aiorazabala** [comment]
Beta version done! 
https://github.com/aiorazabala/qmethod/wiki/Graphical-user-interface-for-qmethod-(beta)

The code is stored at the university server for the moment---storing it in github was being cumbersome to download due to the https protocol :S
