### ISSUE TITLE
support for named factors

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#69]
In preparing factor array visualizations, as well as other reports, I find myself wanting to use *named* factors – something meaningful and short to refer to a factor, as informed by a preliminary factor interpretation, as, for example ``resentment factor`` (in my case) or something.

I'm now coding this as an option into `array.viz.R` as per #14 but I'm wondering whether there isn't a deeper, more consistent way to do this.

I often find myself having to manually edit reports and edit colnames etc, and that gets old quickly.

Or maybe this is adding unnecessary overhead? I'm not sure.

**Comment by aiorazabala** [comment]
`results <- q.factor.names(results, names = c("good", "bad", "ugly")) `

**Comment by maxheld83** [comment]
out of two options:

1. make names an option for `q.method.R`
2. have a separate function that will go through the results object and rename columns etc.

**2** is preferable, because it makes sense chronologically (you first extract, then name factors), and it reduces the risk of mixing up names and factors (for example, when the rotation changes or something).
Naming factors should be an explicit thing you do, not an option – that's what option 2 accomplishes.

Thanks for thinking this through, @aiorazabala !

**Comment by maxheld83** [comment]
is it feasible to have this for 1.4.0? Would be nice to have it so that `array.viz.R` can rely on it.

**Comment by aiorazabala** [comment]
added function `q.fnames()`
the function `plot` for objects of class `QmethodRes` objects has actually an option if you wish to personalise the names (check the documentation)

**Comment by maxheld83** [comment]
this is really elegant and practical! Thanks so much for adding that so quickly, @aiorazabala !
