### ISSUE TITLE
have qdc report differences in zscores, not absolutes

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#70]
It appears that `qdc.R` currently returns *absolute* differences in zscores, negating the direction of the difference.
I understand that that makes sense for the significance test, but it makes for a little unintuitive reading.

Would it maybe make sense to have `qdc.R` report the actual differences in zscores here, including negatives?

**Comment by aiorazabala** [comment]
Good point!

**Comment by aiorazabala** [comment]
Incorporated into #77

**Comment by maxheld83** [comment]
maybe we should keep this open until it is fixed?
I think sometimes atomic, individual issues can be easier to track than lists such as #77

**Comment by aiorazabala** [comment]
Yup
