### ISSUE TITLE
results includes inconvenient scientific notation

### ISSUE THREAD

**Issue by VerenaKasztantowicz** [aiorazabala/qmethod#73]
I was just exploring my results, and it appears that `qmethod` sometimes produces results with (inconsistent) scientific notation, such as `f2` in the below dataframe.

I am guessing this is because there is one (or several) really really small numbers in `f2`, causing R to render the whole column in scientific notation.

Not a real bug, just makes it a little hard to read the `loa` output.

```
                     f1            f2          f3          f4
andrea      0.62764412 -8.872812e-02  0.40324113 -0.12458863
anna        0.52512449  2.993066e-01  0.23751002  0.24946101
antje       0.48152388  2.588302e-01  0.47471189  0.26319114
...
```

**Comment by maxheld83** [comment]
as per [Stack Exchange](http://stackoverflow.com/questions/5352099/how-to-disable-scientific-notation-in-r) there is a **global** option to make R print in non-scientific notation:

```
options(scipen=999)
```

**Comment by maxheld83** [comment]
we could also wrap results in

```
format(functionResult, scientific=FALSE);
```

or

```
as.integer(functionResult);
```

but I'd like to know @aiorazabala what she has to say about it before.

**Comment by aiorazabala** [comment]
or 
```{r}
round(results$loa, digits=2)
```
This is more of a general R thing; R tries to be clever when printing numeric values, and it's often inconvenient scientific notation, but that happens with all packages.

**Comment by maxheld83** [comment]
uh, I see, of course.
I'm wondering whether it might still make sense to do this wrapping (`format(functionResult, scientific=FALSE)`) *inside* `qmethod`, as scientific notation might bewilder R and `qmethod` newbies.
Or maybe Occam's razor dictates that this be closed?

What do you think @VerenaKasztantowicz ?

**Comment by aiorazabala** [comment]
OK, added to #77

**Comment by aiorazabala** [comment]
Added `format(loa, scientific=FALSE))` to objects 3 and 5 (`loa` and `zsc`)

**Comment by aiorazabala** [comment]
Done.

**Comment by maxheld83** [comment]
great @aiorazabala – this isn't on here yet though, right?

(Just FYI, you can conveniently link *issues* with *commits* by mentioning issues in commit messages -> https://help.github.com/articles/closing-issues-via-commit-messages/
You can also just mention them by adding `#101` or something to a commit message.)
