### ISSUE TITLE
significance test for *CONSENSUS* statements?!

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#78]
I was just looking at some `array.viz.R` visualizations and something odd occurred to me: 

When an item is *not* found to be significantly distinguishing between any pair of factors, we consider it a *consensus*, which seems to imply that the item is in the same position on other factors.
But strictly speaking, that does not seem to follow.
Just because an item is *not* significantly distinguishing, the inverse does not follow – namely that it would be at the same position.
All that we know is that we can't be >95% certain that it is in a *different* position.

This seems to be a conventional way of referring to to consensus items, I wonder though, whether it makes sense.

Could there be another statistical test to test for *same* position (true consensus)?

Is this making sense?

**Comment by aiorazabala** [comment]
I understand. This is the way consensus are found according to Brown (1980). 

It actually follows standard hypothesis testing in statistics, meaning that we reject the hypothesis that two items are in the same position, where their z scores are significantly different at .95. One could formulate the opposite hypothesis, i.e. reject that two items are different when they do not differ at a .95.

PQMethod is even less stringent, and considers consensus those statements which, for some pairs of factors, are statistically different, but with a less stringent p-value (see 'Validation' in my paper in the R journal).

I think this is more of a question for the mailing list.

**Comment by maxheld83** [comment]
agreed.
Thanks for weighing in.
My concern is more of a semantic one, then – we shouldn't necessarily be speaking of "consensus" items, as much as of un-rejected H0s.

This can be closed.
