### ISSUE TITLE
document Q method decision tree

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#81]
It occurs to me that there is quite a lot of consequential, sometimes controversial decisions to be taken in the course of a q analysis, including, for example:
1. extraction method (centroid #15 , PCA, principal axis factoring #20 )
2. judgmental ( #13) or automatic rotation?
3. rotation method? (varimax, equamax #28)
4. number of factors to be extracted (Scree plot, parallel analysis #68 )
   5 ... etc.

In the long run, I'd like `qmethod` to be supplemented by a documentation page (on the wiki) that explicates each of these steps, points to relevant literatures, issues and `qmethod` functions.

This will take _a lot_ of time, and it's probably a publication in itself, but still.

Maybe that would be a more productive way to encourage good statistical judgment as per #21

**Comment by maxheld83** [comment]
duplicate https://github.com/QWrks/pensieve/issues/255

**Comment by aiorazabala** [comment]
Key research decisions are listed and reported in Fig 1 in this paper, and explained in this section: https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0148087#sec006

These are now highlighted in the wiki https://github.com/aiorazabala/qmethod/wiki/Reporting-a-Q-study
