### ISSUE TITLE
qmethod list announcement: 1.3.0.

### ISSUE THREAD

**Issue by maxheld83** [aiorazabala/qmethod#82]
@aiorazabala and @maxheld agreed that we should put out a new list announcement to qmethod, once the below stuff is done and on `CRAN`.

covering:

- [x] import/export functions
- [ ] small fixes
- [ ] cookbook (once vetted by Job etc.)
- [x] make.cards.R
- [ ] invitation to join the discussion / request features on the repo
- [ ] named factors

This will probably be largely identical with the release notes to 1.3.0.

We can draft the email together right here in this issue, or in the release notes here on github.

I think @aiorazabala should send the email.

**Comment by maxheld83** [comment]
eh, screw this, we can draft the release note right here in the draft release: https://github.com/aiorazabala/qmethod/releases

I'd also suggest that we sent out exactly what we draft in the release note.

@aiorazabala could you maybe also add the zip you're uploading to CRAN as a binary? That way we've got it all covered.

**Comment by maxheld83** [comment]
@aiorazabala do you still plan on announcing the update to the Qmethod list?
Let me know if I can do anything to help.
I drafted a release note here: https://github.com/aiorazabala/qmethod/releases
You can go ahead and edit / disregard that.
I think we might use the same release note on here as on a possible message to the list.

**Comment by maxheld83** [comment]
I wanted to mention the release on my twitter account at some point, but I don't want to do it before you announce, since it is your package.

**Comment by aiorazabala** [comment]
please feel free!

**Comment by maxheld83** [comment]
this is done, too, I'm closing the milestone now
