### ISSUE TITLE
P2P review of pull 52 import etc. functions

### ISSUE THREAD

**Issue by aiorazabala** [aiorazabala/qmethod#84]
#### 2. Testing the functions:
Please note that the comments below may be due to my ignorance about all the details of the functions.

##### - `import.q.sorts()`
   - the result is an array of two matrices, can this object (or its parts) be directly input into `qmethod()`? e.g. `qmethod(q.sorts[[1]])`
     - One can do `qmethod(data.frame(q.sorts), 2)` perhaps the output of the `import.q.sorts()` function can be in the form of a list of one or more matrices/ data.frames instead?
   - in the example, setting `manual.lookup = NULL` did not return any values (I tried by copying the *.CSV files into `.../inst/extdata/importexample/qsorts/JaneDoe.csv`
   - argument `q.set`, Is it used? (not visible in the output)
   - argument `manual.lookup`, setting it to `NULL` in the example gave an error: 

     `Error in import.q.sorts(q.sorts.dir = path.sorts, q.set = importexample$q.set,  : The qsort in ...extdata/importexample/qsorts/before/JaneDoe.csv contains id i02 not defined in the lookup table.`

##### - `import.q.feedback()`
  - argument `manual.lookup`, setting it to `NULL` in the example gave a warning (and results with all values = NA): 

     `Warning message: In import.q.feedback(q.feedback.dir = path.feedback, q.sorts = importexample$q.sorts,  :  Feedback in .../importexample/feedback/after/JohnDoe.csv under id i01 is not defined in the lookup table and was ignored.`

##### - `build.q.set()`
   - argument `q.distribution`, Is it used?
   - At the moment there is no difference between `build.q.set` and `import.q.concourse`, in terms of the output. Is `build.q.set` used for something else specifically? Otherwise we could keep this function in backlog until it adds something different.

##### - `make.cards()`
  - the example gives an error, although I got the PDF output (the error is the same as in `R CMD check` above)
  - If it's not much of a hassle, I'd suggest to add an argument `filename`

##### - `array.viz()` - Untested (although I got a nice *.PDF in the `R CMD check`

**Comment by aiorazabala** [comment]
`R CMD check -as-cran ...` *.LOG file (two issues):

```{r}
* using log directory ‘.../qmethod.Rcheck’
* using R version 3.1.2 (2014-10-31)
* using platform: x86_64-pc-linux-gnu (64-bit)
* using session charset: UTF-8
* checking for file ‘qmethod/DESCRIPTION’ ... OK
* this is package ‘qmethod’ version ‘1.3.01’
* checking package namespace information ... OK
* checking package dependencies ... OK
* checking if this is a source package ... OK
* checking if there is a namespace ... OK
* checking for executable files ... OK
* checking for hidden files and directories ... OK
* checking for portable file names ... OK
* checking for sufficient/correct file permissions ... OK
* checking whether package ‘qmethod’ can be installed ... WARNING
Found the following significant warnings:
  Warning: replacing previous import by ‘ggplot2::%+%’ when loading ‘qmethod’
See ‘.../qmethod.Rcheck/00install.out’ for details.
* checking installed package size ... OK
* checking package directory ... OK
* checking DESCRIPTION meta-information ... OK
* checking top-level files ... OK
* checking for left-over files ... OK
* checking index information ... OK
* checking package subdirectories ... OK
* checking R files for non-ASCII characters ... OK
* checking R files for syntax errors ... OK
* checking whether the package can be loaded ... OK
* checking whether the package can be loaded with stated dependencies ... OK
* checking whether the package can be unloaded cleanly ... OK
* checking whether the namespace can be loaded with stated dependencies ... OK
* checking whether the namespace can be unloaded cleanly ... OK
* checking loading without being on the library search path ... OK
* checking dependencies in R code ... OK
* checking S3 generic/method consistency ... OK
* checking replacement functions ... OK
* checking foreign function calls ... OK
* checking R code for possible problems ... OK
* checking Rd files ... OK
* checking Rd metadata ... OK
* checking Rd cross-references ... OK
* checking for missing documentation entries ... OK
* checking for code/documentation mismatches ... OK
* checking Rd \usage sections ... OK
* checking Rd contents ... OK
* checking for unstated dependencies in examples ... OK
* checking contents of ‘data’ directory ... OK
* checking data for non-ASCII characters ... OK
* checking data for ASCII and uncompressed saves ... OK
* checking examples ... ERROR
Running examples in ‘qmethod-Ex.R’ failed
The error most likely occurred in:

> ### Name: make.cards
> ### Title: Q methodology: produce printable cards for Q study with ID and
> ###   full item wording
> ### Aliases: make.cards
> 
> ### ** Examples
> 
>  ## Make cards from importexample
>  data(importexample)
>  make.cards(importexample$q.set)


processing file: /home/aiora/Deskargak/qmethod.Rcheck/qmethod/cardtemplates/AveryZweckformC32010.Rnw

  |                                                                       
  |                                                                 |   0%
  |                                                                       
  |......................                                           |  33%
  ordinary text without R code


  |                                                                       
  |...........................................                      |  67%
label: make.cards (with options) 
List of 4
 $ results: chr "asis"
 $ echo   : logi FALSE
 $ warning: logi FALSE
 $ message: logi FALSE


  |                                                                       
  |.................................................................| 100%
  ordinary text without R code


output file: AveryZweckformC32010.tex

Error in texi2dvi(file = file, pdf = TRUE, clean = clean, quiet = quiet,  : 
  Running 'texi2dvi' on 'AveryZweckformC32010.tex' failed.
LaTeX errors:
! Package babel Error: Unknown option `ngerman'. Either you misspelled it
(babel)                or the language definition file ngerman.ldf was not foun
d.

See the babel package documentation for explanation.
Calls: make.cards -> knit2pdf -> <Anonymous> -> texi2dvi
Execution halted
```

**Comment by aiorazabala** [comment]
Hey @maxheld83 thank you for this, I'm happy that I finally checked your new functions, thank you for sending it through!

Please feel free to merge the pull request 52 (all this) into `master` now (I'll delete `dev` ASAP). I'll then wait until the `R CMD check` is clean, before making the release.

Please take the comments above on each functions as mere suggestions; at the end of the day, it's your work!

**Comment by maxheld83** [comment]
thanks for the great and thorough feedback, @aiorazabala !

I'll go over that and comment on it one-by-one over at the actual pull request to which this pertains -> #52 

I'll close this then.
